version: "3.9"

services:
  webchat-nodejs:
    build: .
    ports:
      - "8080"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - TOKEN_SECRET=${TOKEN_SECRET}
    networks:
      backend:
    deploy:
      replicas: 1

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      backend:


  nginx:
    image: nginx:latest
    ports:
      - "8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      backend:
        ipv4_address: 172.2.0.254
    depends_on:
      - webchat-nodejs

networks:
  backend:
    ipam:
      config:
        - subnet: 172.2.0.0/24
