version: "3.9"

services:
  webchat-nodejs:
    build: .
    ports:
      - "8080"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - TOKEN_SECRET=${TOKEN_SECRET}
    networks:
      webchat:
    deploy:
      replicas: 1

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      webchat:
        ipv4_address: 172.2.0.250

  nginx:
    image: nginx:latest
    ports:
      - "8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      webchat:
        ipv4_address: 172.2.0.251
    depends_on:
      - webchat-nodejs

networks:
  webchat:
    external: true
